version: "3.9"

services:

  redis:
    #定义主机名
    container_name: myredis
    #使用的镜像；注意这里的版本要与第2步redis版本一致
    image: redis:7.0.4
    #容器的映射端口
    ports:
      - 6379:6379 #注意第二个端口必须是redis.conf中的端口号
    command: redis-server /usr/local/etc/redis/redis.conf #以配置文件方式启动redis
    #定义挂载点
    volumes:
      - /redis/data:/data #挂载/docker-compose/redis/data至容器
      - /redis/conf/redis.conf:/usr/local/etc/redis/redis.conf #挂载conf至容器   
      - /redis/logs:/logs
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    #docker 重启后，容器自启动
    restart: always
  
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    volumes:
      - /mysql/mydir:/mydir
      - /mysql/datadir:/var/lib/mysql
      - /mysql/conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306